vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}

direction: right

Main Site: {
  style.stroke: green
  WG server: {
    shape: rectangle
    icon: https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/wireguard.svg
    style: {
      stroke: maroon
    }
    WG0: WG0: 10.20.1.1 {
      style: {
        animated: true
        stroke: maroon
      }
    }
  }
}

Remote User: {
  style.stroke: green
  shape: person
  WG client: {
    shape: rectangle
    icon: https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/wireguard.svg
    style: {
      stroke: maroon
    }
    WG0: WG0: 10.20.1.10 {
      style: {
        animated: true
        stroke: maroon
      }
    }
  }
}

Internet: {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
}

title: |md
  # Remote access example
| {
  near: top-center
}

subnet main site: |md
  # Subnet 10.10.0.0/16
| {
  near: top-right
}

Remote User.WG client.WG0 -> Internet: WG tunnel (10.20.1.0/24) {
  style: {
    animated: true
    stroke: maroon
  }
}

Internet -> Main Site.WG server.WG0: WG tunnel (10.20.1.0/24) {
  style: {
    animated: true
    stroke: maroon
  }
}
