vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}

direction: right

Main Site: {
  style.stroke: green
  VPN server: {
    shape: rectangle
    style: {
      animated: true
      stroke: red
    }
  }
}

User 1: {
  shape: person
  style: {animated: true}
}

User 2: {
  shape: person
  style: {animated: true}
}
User 3: {
  shape: person
  style: {animated: true}
}

Internet: {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
}

title: |md
  # VPN Remote client setup
| {
  near: top-center
}

User 1 -> Internet: VPN tunnel {
  style: {
    animated: true
    stroke: blue
  }
}

User 2 -> Internet: VPN tunnel {
  style: {
    animated: true
    stroke: blue
  }
}

User 3 -> Internet: VPN tunnel {
  style: {
    animated: true
    stroke: blue
  }
}

Internet -> Main Site.VPN server: VPN tunnel {
  style: {
    animated: true
    stroke: blue
  }
}

Internet -> Main Site.VPN server: VPN tunnel {
  style: {
    animated: true
    stroke: blue
  }
}

Internet -> Main Site.VPN server: VPN tunnel {
  style: {
    animated: true
    stroke: blue
  }
}
