vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}

direction: right

Homelab Network: {
  style.stroke: green
  Fortigate 60E: {
    shape: rectangle
    icon: https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/fortinet.svg
    style: {
      animated: true
      stroke: red
    }
  }

  Proxmox node: {
    shape: square
    icon: https://cdn.jsdelivr.net/npm/@loganmarchione/homelab-svg-assets@latest/assets/proxmox.svg
    style: {
      animated: true
      stroke: orange
    }
  }

  Fortigate 60E -- Cisco SG300: LAG trunk {
    style: {
      animated: true
      stroke: blue
    }
  }
}

Internet: {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
  style: {
    animated: true
  }
}

Internet -- Fortigate 60E: {
  style: {
    animated: true
    stroke: red
  }
}
