vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    #theme-id: 300
  }
}

direction: right

Homelab-net {
    Fortigate: {
        shape: image
        icon: https://icons.terrastruct.com/infra%2F003-firewall.svg
        style {
            animated: true
        }
    }

    Cisco SG300: {
        style {
            animated: true
        }
    }

    Proxmox node : {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F112-server.svg
        style {
            animated: true
        }
    }

    Wi-Fi AP: {
        shape: circle
        style {
            stroke: deepskyblue
            double-border: true
            animated: true
        }
    }

    Synology DS223: {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F117-database.svg
        style {
            animated: true
        }
    }

    Fortigate -- Cisco SG300: LAG trunk {style.animated: true}
    Fortigate -- Cisco SG300: LAG trunk {style.animated: true}
    Fortigate -- Proxmox node: DMZ trunk {style.animated: true}

    Cisco SG300 -- Proxmox node: LAG trunk {style.animated: true}
    Cisco SG300 -- Proxmox node: LAG trunk {style.animated: true}
    Cisco SG300 -- Synology DS223 {style.animated: true}
    Cisco SG300 -- Wi-Fi AP: trunk {style.animated: true}
}


Internet: {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
    style {
        animated: true
    }
}

ISP router: {
    shape: image
    icon: https://icons.terrastruct.com/tech%2Frouter.svg
    style {
        animated: true
    }
}
Internet -- ISP router -- Homelab-net.Fortigate {style.animated: true}
