vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}

direction: right

Homelab Network {
    style.stroke: green
    Fortigate 60E: {
        shape: image
        icon: https://icons.terrastruct.com/infra%2F003-firewall.svg
        style {
            animated: true
        }
    }

    Cisco SG300: {
        style {
            animated: true
        }
    }

    Proxmox node : {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F112-server.svg
        style {
            animated: true
        }
    }

    UAP-nanoHD: {
        shape: circle
        style {
            stroke: deepskyblue
            double-border: true
            animated: true
        }
    }

    Synology DS223: {
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F117-database.svg
        style {
            animated: true
        }
    }

    Fortigate 60E -- Cisco SG300: LAG trunk {style.animated: true}
    Fortigate 60E -- Cisco SG300: LAG trunk {style.animated: true}
    Fortigate 60E -- Proxmox node: DMZ trunk {style {animated: true
                                                    stroke: red}}

    Cisco SG300 -- Proxmox node: LAG trunk {style.animated: true}
    Cisco SG300 -- Proxmox node: LAG trunk {style.animated: true}
    Cisco SG300 -- Synology DS223 {style.animated: true}
    Cisco SG300 -- UAP-nanoHD: trunk {style.animated: true}
}


Internet: {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F140-internet.svg
    style {
        animated: true
    }
}

ISP router: {
    shape: image
    icon: https://icons.terrastruct.com/tech%2Frouter.svg
    style {
        animated: true
    }
}
Internet -- ISP router: 500Mb/s Fiber {style.animated: true}
ISP router -- Homelab Network.Fortigate 60E: Redundant link {style.animated: true}
ISP router -- Homelab Network.Fortigate 60E: Redundant link {style.animated: true}
